### ISSUE TITLE
Vietnamese source update: nettruyen

### ISSUE THREAD

**Issue by Metallizz** [Skittyblock/aidoku-community-sources#105]
Hi Dev 

Nettruyen (a big Vietnamese source) has updated their new domain. 
Previous: nettruyenme.com
New domain: nettruyenin.com
Thus come we Vietnamese unable to search or read using the Aidoku app anymore. 
If you have sometime, kindly please help update the source list.

Much appreciate and have a nice weekend!
Thank you for this app. 
 
![CE9312D3-8CE3-4AE8-A2E9-DF7388D33930](https://user-images.githubusercontent.com/118589638/202837335-bca08e94-8da8-4ef8-b3d5-d4db3194dba7.png)

**Comment by Skittyblock** [comment]
Thanks for reporting, should be fixed now.
