### ISSUE TITLE
Vietnamese Nettruyen changed their domain

### ISSUE THREAD

**Issue by dtsdt** [Skittyblock/aidoku-community-sources#118]
Nettruyen changed their domain to https://www.nettruyenking.com/

Please update the source. Thank you for your great app.

**Comment by QuanTrieuPCYT** [comment]
> Nettruyen changed their domain to https://www.nettruyenking.com/
> 
> Please update the source. Thank you for your great app.
Fixed with #119 but with a different domain

**Comment by QuanTrieuPCYT** [comment]
> Nettruyen changed their domain to https://www.nettruyenking.com/
> 
> Please update the source. Thank you for your great app.

Fixed in #119 but with a different domain.
