### ISSUE TITLE
Copymanga

### ISSUE THREAD

**Issue by STSnaive** [Skittyblock/aidoku-community-sources#139]
More Chinese source  would be great for Chinese users, here's some my recommended websites. 

Name: Copymanga (拷贝漫画)
Link: https://copymanga.site/
Language: Chinese

**Comment by Skittyblock** [comment]
Please make separate issues for multiple requests. This one can be for Copymanga.

**Comment by siwang2011** [comment]
copymanga.site is Unable to access.
How can I change it to copymanga.tv?

**Comment by Skittyblock** [comment]
Make a new issue if the source is having issues
