### ISSUE TITLE
NineManga

### ISSUE THREAD

**Issue by Sslimiiii** [Skittyblock/aidoku-community-sources#158]
I want to request this sources for hispanic readers

**Comment by Skittyblock** [comment]
Make separate issues for separate sources

**Comment by daarkdemon** [comment]
@Skittyblock ninemanga is already present in draft PR. Let me know if any changes required

**Comment by Skittyblock** [comment]
if it's ready for review you should mark it as not a draft. I figure all drafts still needed changes before being reviewed.
