### ISSUE TITLE
Add manga chan plsss

### ISSUE THREAD

**Issue by mehyouarenoisy** [Skittyblock/aidoku-community-sources#166]
Can you please add Manga-chan or Mangalib or any other russian source?

**Comment by mehyouarenoisy** [comment]
https://mangalib.me/
Mangalib

https://manga-chan.me/catalog
Manga chan

**Comment by Skittyblock** [comment]
https://github.com/Skittyblock/aidoku-community-sources/tree/main/src/rust/multichan/sources/mangachan
