### ISSUE TITLE
Hentai2Read

### ISSUE THREAD

**Issue by Samk19** [Skittyblock/aidoku-community-sources#180]
Hentai2read
Link: https://hentai2read.com

Reason: large NSFW source with all chapters of the title combined into one (also has better quality of some titles)

**Comment by itss0n1c** [comment]
I'm on the job 🫡

**Comment by Samk19** [comment]
> I'm on the job 🫡

Thanks mate.

Any progress?

**Comment by Skittyblock** [comment]
pr is open but it needs some more changes before being merged
