### ISSUE TITLE
WebtoonXYZ

### ISSUE THREAD

**Issue by Kapoopy** [Skittyblock/aidoku-community-sources#196]

**Comment by Skittyblock** [comment]
assuming https://www.webtoon.xyz/

**Comment by Roal1115** [comment]
Where i can check the documentation to create the source for this page?? im interested in this source and im able to help with the source

**Comment by Skittyblock** [comment]
[The contributing guide](https://github.com/Skittyblock/aidoku-community-sources/blob/main/.github/CONTRIBUTING.md) should help, as well as the pins in #source-dev on the Discord server.
