### ISSUE TITLE
Source requests: Baozimh, Cocomanga

### ISSUE THREAD

**Issue by DevCoz** [Skittyblock/aidoku-community-sources#22]
https://www.baozimh.com/
https://www.cocomanga.com/

Many thanks..

**Comment by DevCoz** [comment]
Baozimh mirror site：cn.baozimh.com, cn.webmota.com,tw.baozimh.com, tw.webmota.com,www.baozimh.com, www.webmota.com

**Comment by aphronyx** [comment]
**Baozimh** was added -> #312 
**Cocomanga** changed its domain name to **COLAMANHUA** -> #279
