### ISSUE TITLE
I would like to add this site if possible please

### ISSUE THREAD

**Issue by musallam161** [Skittyblock/aidoku-community-sources#257]
(1)https://ozulscans.com (2)https://team1x1.fun (3)https://mangaflame.org (4)https://mangaatrend.com (5)https://azoranov.com (6)https://aresmanga.net (7)https://vexmanga.net (8)https://galaxymanga.org (9)https://mangatime.co/home-dark1/ (10)https://mangaspark.com (11)https://www.mangasol.com (12)https://mangalek.com (13)https://hizomanga.com (14)https://mangaprotm.com

**Comment by Skittyblock** [comment]
Some of those are duplicates, but each source needs to have a separate issue created if you would like to request them
