### ISSUE TITLE
Please fix this manga

### ISSUE THREAD

**Issue by musallam161** [Skittyblock/aidoku-community-sources#278]
![image](https://user-images.githubusercontent.com/93211711/229814481-71bb17c5-d44c-49d2-9473-862ee5cf4e5d.jpeg)![image](https://user-images.githubusercontent.com/93211711/229814535-6e6dea37-b532-4111-857d-d267ad924f6e.png)

**Comment by Skittyblock** [comment]
remove and reinstall the sources
