### ISSUE TITLE
Arabic sources

### ISSUE THREAD

**Issue by vTorex** [Skittyblock/aidoku-community-sources#300]
We need to add some arabic sources plz, the sources now all broken, there is some link to the best arabic sources i hope you add

AzoraManga: https://azoranov.com

Mangaswat: https://swatmanga.me 

TeamX: https://team1x1.fun

Ozulscans: https://ozulscans.com

Note: mangaswat is already there but the old website:(

Thx for all <3

**Comment by Skittyblock** [comment]
please make separate issues for each source request
