### ISSUE TITLE
MangaSwat

### ISSUE THREAD

**Issue by vTorex** [Skittyblock/aidoku-community-sources#305]
Plz add this source for arabic language

Name: MangaSwat

Link: https://swatmanga.me

**Comment by naufaljct48** [comment]
SwatManga already available

**Comment by vTorex** [comment]
Old website ):

**Comment by naufaljct48** [comment]
![image](https://user-images.githubusercontent.com/30202760/233876749-3a237b24-2576-4b14-b3d8-1fde001e3354.png)
I tried to fix this, but idk why the chapters won't load
![image](https://user-images.githubusercontent.com/30202760/233876679-16c98b9c-8914-42a2-8330-9a130b5b86ef.png)

**Comment by Skittyblock** [comment]
sounds like the source needs fixing then
