### ISSUE TITLE
Koushoku (ksk.moe)

### ISSUE THREAD

**Issue by Astrangebirdy** [Skittyblock/aidoku-community-sources#324]
Since the source nana (nana.my.id) is dead, please can you add Koushoku : https://ksk.moe/

**Comment by Skittyblock** [comment]
koushoku isn't worth maintaining due to their anti-scraping measures, and was removed because of it https://github.com/tachiyomiorg/tachiyomi-extensions/pull/13329

**Comment by Skittyblock** [comment]
no, paperback uses a different extension system.
