### ISSUE TITLE
Sushi-Scan pages fail to load

### ISSUE THREAD

**Issue by aesthesky** [Skittyblock/aidoku-community-sources#328]

**Comment by Skittyblock** [comment]
please provide more info -- which manga?

**Comment by aesthesky** [comment]
Well, for starters, when I open the app I get a cloudfare pop-up.
Also, in the browse section, sushiscan takes much longer to load than the other sources.
As for the scans failing to load, honestly it depends. I don't know what defines why some work and others don't.
For example, _Chainsaw Man, Mashle, Black Clover, One Punch Man or Vagabond_ do not work. A message telling me to reload the page appears, which doesn't work.
But _One Piece, Bleach, Kingdom, Solo Leveling or Jujutsu Kaisen_ works fine. 
That said, the problem persists with the same ones since a few weeks now, if that helps.
I hope my explanation will be useful and thanks again for the work you do.

**Comment by Skittyblock** [comment]
Taking longer to load is just due to the source having poor servers and there's nothing we can do about that. But yes, pages do seem to fail to load on manga like Chainsaw Man.

**Comment by CptBigBen** [comment]
Hello, thanks for your dedicated hard Work!
On my end sushi scan isn’t loading anything anymore.
Would you have any update on that ticket ?
If you need any logs or info please LMK

**Comment by K0Konut** [comment]
Sushi scan still doesn't work. All the manga are all loading for infinity. Nothing work. I try uninstall and install back just after and this doesn't work and so on. How could we fix it? Because it s the only French sources who work
