### ISSUE TITLE
e-Hentai

### ISSUE THREAD

**Issue by alvinchan-mc** [Skittyblock/aidoku-community-sources#336]
Language: Multi (NSFW)
Site: https://e-hentai.org/
Template source :  https://github.com/tachiyomiorg/tachiyomi-extensions/blob/5a8618f004a4a8560e6d0d480805bffe4794bd10/src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt

**Comment by Skittyblock** [comment]
#84
