### ISSUE TITLE
Asura Scans changing identifiers

### ISSUE THREAD

**Issue by ClassicalCoder101** [Skittyblock/aidoku-community-sources#382]
I’ve been coming across a bug where whenever a manhwa from Asura Scans updates, it gets added to the Library as a duplicate with reset read/unread information. Below are examples of a particular case:
![IMG_2073](https://github.com/Skittyblock/aidoku-community-sources/assets/33522944/a5489281-3f4e-4664-a3c1-1ce6a12985bf)
![IMG_2074](https://github.com/Skittyblock/aidoku-community-sources/assets/33522944/6f797a89-061a-4a36-95f8-fd8768083fcd)
![IMG_2075](https://github.com/Skittyblock/aidoku-community-sources/assets/33522944/5ac213af-0375-4034-8942-a6b197ce8ad5)
![IMG_2076](https://github.com/Skittyblock/aidoku-community-sources/assets/33522944/5fe4d1be-ca67-40b1-8acc-d5165972c266)
I do not know if this issue is specific to Asura Scans or applies to other ones as well, but whenever this happens, as seen in the screenshots, the older version of the source just stays there without the addition of the new chapter.
I’m on version 0.6.3 build 1, iOS 16.5, iPhone 13

**Comment by KaBankz** [comment]
This is a common issue with Asura, they change the identifiers of their manhwa's occasionally, which causes existing library entries from them to break.

To fix this, all you have to do is migrate from Asura back into Asura. The migrate option is in the top right of the browse tab (double arrow icon).

**Comment by ClassicalCoder101** [comment]
> This is a common issue with Asura, they change the identifiers of their manhwa's occasionally, which causes existing library entries from them to break.
> 
> To fix this, all you have to do is migrate from Asura back into Asura. The migrate option is in the top right of the browse tab (double arrow icon).

Thank you! This was helpful :)

**Comment by Skittyblock** [comment]
Doesn't seem to be a good solution for this at the moment, but one might hopefully crop up in the future
