### ISSUE TITLE
MangaLib

### ISSUE THREAD

**Issue by Zzold** [Skittyblock/aidoku-community-sources#419]
It would be cool if you could add that :)
Link: mangalib.me
Language: Russia

**Comment by Skittyblock** [comment]
https://mangalib.org? https://mangalib.me gives me a 404

**Comment by NicolBO** [comment]
> https://mangalib.org? https://mangalib.me gives me a 404

Yep, this sites are equal to each other. I think that mangalib.me is only for Russia. And sorry for my bad English)

**Comment by Zzold** [comment]
> https://mangalib.org? https://mangalib.me gives me a 404

.org is a mirror of the site, because .me works only in Russia, you can add .org to make the site work correctly for everyone, sorry for this mistake, I just found out about it myself now

**Comment by Skittyblock** [comment]
completed with #634
