### ISSUE TITLE
Sushi-scan broken

### ISSUE THREAD

**Issue by HokaGeekHaruno** [Skittyblock/aidoku-community-sources#435]
Sushi-scan source have an issue and it the best french one so it pretty annoying 

https://github.com/Skittyblock/aidoku-community-sources/assets/88339222/4ca43524-f240-47d9-a248-0f921d3deb10

**Comment by FoxyDr3am** [comment]
This can't be fix
You just need to wait for the cloudflare connection issue to fix by itself

**Comment by HokaGeekHaruno** [comment]
how much time it usually take ?

**Comment by FoxyDr3am** [comment]
Idk some weeks or months

**Comment by FoxyDr3am** [comment]
Use this at the meantime 

https://aidoku.app/add-source-list/?url=https://raw.githubusercontent.com/Moomooo95/aidoku-french-sources/gh-pages/

**Comment by HokaGeekHaruno** [comment]
alr thx

**Comment by MozkaGit** [comment]
It's broken again. @FoxyDr3am can you explain what's the issue with the cloudflare ? Why is it so unstable? Breaks every week

**Comment by FoxyDr3am** [comment]
Hmm idk maybe the owner of the site changed something. Maybe they put the security on high for a moment this is why it's appearing. The pop up is a security measure put in place by the owners or cloudflare to protect websites from malicious bots and automated attacks.So you will just need to wait we can't do anything about it

**Comment by HokaGeekHaruno** [comment]
It's been a month and it still doesn't work. Besides, we don't have a pop-up asking us to confirm that we are not a robot, could that be the cause of the problem?

**Comment by FoxyDr3am** [comment]
@Skittyblock you should close this one 
For some reason after they update comick the cloudflare bypass is working again for sushiscan but I can't confirm if it's working for everyone

**Comment by Skittyblock** [comment]
this was fixed by ba19cb50650c8e084948353f54923524336adedf
