### ISSUE TITLE
French source (multi)

### ISSUE THREAD

**Issue by Akeru60** [Skittyblock/aidoku-community-sources#484]
Hello, here is a list of French sources plz :

Fr-Scan (https://fr-scan.cc/)
Scantrad-Union (https://scantrad-union.com/)
Astral Manga (https://astral-manga.fr/)
Shadow Trad (https://shadowtrad.net/)
Perf Scan (https://perf-scan.fr/)
LegacyScans (https://legacy-scans.com/)
FMTeam (https://fmteam.fr/)
Japscan (https://www.japscan.lol/)
Bentomanga (https://bentomanga.com/)

It's a long list, but it covers 80-90% of the best-known French-language sites. Many thanks for your work!

**Comment by Skittyblock** [comment]
separate source requests should go into separate issues
