### ISSUE TITLE
包子漫画

### ISSUE THREAD

**Issue by monkey1019** [Skittyblock/aidoku-community-sources#485]
There are some issues with the source of the baozi manga. The original website has not changed, but the images are not loaded.

**Comment by aphronyx** [comment]
it works fine on my device:
![IMG_4F9FE7BA8ABF-1](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/9a998a0c-cf3b-412e-8363-6a615914871e)

try clearing the network cache in the app:
![IMG_F4B1FA71462D-1](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/a921c842-76f2-477b-87ee-bc705adffd7b)

if it still happens, please provide more details:

- which manga
- which chapter
- when did it start to happen

**Comment by monkey1019** [comment]
i also found the questions from this source that all of them are unable to load yesterday



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Alan Tan ***@***.***&gt;
发送时间: 2023年12月6日 20:46
收件人: Skittyblock/aidoku-community-sources ***@***.***&gt;
抄送: monkey1019 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Skittyblock/aidoku-community-sources] 包子漫画 (Issue #485)





 
I believe they did updated the website, now they may break one chapter into more than one. For example: 超級鑑寶師 第19話
 https://www.baozimh.com/comic/chapter/chaojijianbaoshi-fengluandao/0_18.html
 https://www.baozimh.com/comic/chapter/chaojijianbaoshi-fengluandao/0_18_2.html
 https://www.baozimh.com/comic/chapter/chaojijianbaoshi-fengluandao/0_18_3.html

**Comment by dodieboy** [comment]
few week ago, my comic still having missing pages, not sure is I'm getting the first 50 or last 50. Will need to test again

**Comment by monkey1019** [comment]
i dont know when wil the problem be repaired.it always tips me that you are offline or there are some troubles with the source website.and all the mangas are not able to be loaded.if it has been repaired，please leave a message



发自我的iPhone


------------------ 原始邮件 ------------------
发件人:&nbsp;Alan Tan ***@***.***&gt;
发送时间:&nbsp;2023年12月6日 22:15
收件人:&nbsp;Skittyblock/aidoku-community-sources ***@***.***&gt;
抄送:&nbsp;monkey1019 ***@***.***&gt;, Mention ***@***.***&gt;
主题:&nbsp;Re: [Skittyblock/aidoku-community-sources] 包子漫画 (Issue #485)






few week ago, my comic still having missing pages, not sure is I'm getting the first 50 or last 50. Will need to test again

—
Reply to this email directly,&nbsp;view it on GitHub, or&nbsp;unsubscribe.
You are receiving this because you were mentioned.





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Alan Tan ***@***.***&gt;
发送时间: 2023年12月6日 20:46
收件人: Skittyblock/aidoku-community-sources ***@***.***&gt;
抄送: monkey1019 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Skittyblock/aidoku-community-sources] 包子漫画 (Issue #485)





 
I believe they did updated the website, now they may break one chapter into more than one. For example: 超級鑑寶師 第19話
 https://www.baozimh.com/comic/chapter/chaojijianbaoshi-fengluandao/0_18.html
 https://www.baozimh.com/comic/chapter/chaojijianbaoshi-fengluandao/0_18_2.html
 https://www.baozimh.com/comic/chapter/chaojijianbaoshi-fengluandao/0_18_3.html

**Comment by aphronyx** [comment]
> i dont know when wil the problem be repaired.it always tips me that you are offline or there are some troubles with the source website.and all the mangas are not able to be loaded.if it has been repaired，please leave a message

@monkey1019 
it’s repaired, but the pr needs to be reviewed by skitty before merged. you could build and update the source by yourself. if you don’t know how to do that, you could dm me on discord

**Comment by dodieboy** [comment]
Wow, just saw your PR. You just rewrite the whole script for 包子

**Comment by aphronyx** [comment]
> Wow, just saw your PR. You just rewrite the whole script for 包子

@dodieboy 
yeah, it was my first source, so the code was a mess. to make it easier to maintain, I decided to rewrite it from scratch.

btw, if you still have the issue you mentioned after update the source, please dm me on discord or create a new issue and tag me
