### ISSUE TITLE
Repair and add

### ISSUE THREAD

**Issue by musallam161** [Skittyblock/aidoku-community-sources#524]
I hope to add these Arabic manga site.                        (1)https://team11x11.com                                (2)https://flixscans.com/webtoons/hoome                   (3)https://mangaflame.org                                     I hope the Swat and Azura manga will be fixed       (1)https://goldragon.me                                     (2)https://azoramoon.com

**Comment by Skittyblock** [comment]
make separate issues for separate source requests or source issues
