### ISSUE TITLE
Manhwax dead

### ISSUE THREAD

**Issue by Velphae** [Skittyblock/aidoku-community-sources#565]
Evening, noticed that hiperdex and manwhax stopped working, endlessly loading or states that it failed to load chapter.

**Comment by FoxyDr3am** [comment]
Hiperdex is just the cloudflare bypass isn't working properly and for ManhwaX website is unavailable/dead

**Comment by Skittyblock** [comment]
make separate issue for separate source issues -- manhwax should be removed if it's dead, and hiperdex needs to be updated to use a different user agent in order to bypass cloudflare

**Comment by Velphae** [comment]
Do you want me to make another issue post? I see you removed manwhax from the title.

**Comment by Skittyblock** [comment]
yes please

**Comment by FoxyDr3am** [comment]
They change domain name from https://manhwax.com to https://manhwax.org

**Comment by webtoonjoon** [comment]
The old manhwax site is basically dead now, and a lot of other popular manga, manhwa, anime, and gallery sites have also changed domains or gone offline over the years. If you're looking for working versions, here are some of the newer sites people are using:

Hentai / Manhwa Sites:
https://manytoon.pro/
https://manhwax.pro/
https://exhentai.co/
https://manhwahentai.pro/
https://mangahentai.pro/

Manga / Manhwa Sites:
https://batoto.one/
https://mangapark.pro/
https://vyvymanga.pro/

Anime / Movie Sites:
https://kissanime.stream/
https://ytsmx.stream/
https://ytsmx.one/
