### ISSUE TITLE
Reader customisation

### ISSUE THREAD

**Issue by HamzaQurayshi** [Skittyblock/aidoku-community-sources#601]
Just noticed how the reader is a bit bare. I thought it would be nice to have a customised way to go to the next/previous page. E.g. maybe have the volume buttons do that, or a motion that signals to do that.

Also a small nitpick that in the reader u can't touch the halves of the screen to go to the next/previous page either. Only option right now is swiping.

**Comment by Skittyblock** [comment]
This is not the repo for the app. You're looking for https://github.com/Aidoku/Aidoku.
However, those issues already exist: https://github.com/Aidoku/Aidoku/issues/107, https://github.com/Aidoku/Aidoku/issues/32
