### ISSUE TITLE
NHentai Source not fully functioning

### ISSUE THREAD

**Issue by Roroca-1** [Skittyblock/aidoku-community-sources#621]
NHentai source cannot find old hentai, with search using title or number
In-App NHentai sorting Popular-All Time returns nothing

**Comment by Skittyblock** [comment]
gonna need an example id that you can't find through the source to test with

**Comment by Roroca-1** [comment]
> gonna need an example id that you can't find through the source to test with

384180

**Comment by Skittyblock** [comment]
replacing this with #638 since no id was provided that can't be searched.
