### ISSUE TITLE
xoxo comics only shows comics on the front page

### ISSUE THREAD

**Issue by kulaid** [Skittyblock/aidoku-community-sources#627]
the site itself has a large selection, however on Aidoku you can only ever access titles which are currently on the front page of the site. You can read the accessible comics without issue

**Comment by Skittyblock** [comment]
Guessing this might be the issue? https://github.com/Skittyblock/aidoku-community-sources/blob/f56d6b11fc4e48e9d2133462dcd7ddd512a810f4/src/rust/wpcomics/sources/xoxocomics/src/lib.rs#L22

Does searching the rest work? Is it just the All list of manga that only shows stuff on the front page or what?

**Comment by kulaid** [comment]
Searching does nothing at all, neither doing changing the list nor trying to filter a genre.

**Comment by kulaid** [comment]
here's two screenshots https://imgur.com/a/DKkx4Wi

**Comment by Skittyblock** [comment]
entire source now broken

**Comment by thebigchile** [comment]
I believe the issue is the URL, it ends with xoxocomicS it shouldn't have a S at the end
