### ISSUE TITLE
French sources don't work

### ISSUE THREAD

**Issue by K0Konut** [Skittyblock/aidoku-community-sources#639]
Is it possible to fix the French sources none of them is working or maybe one or two but not update 

If it s possible to fix them it will be awesome. 

Like sushi scan 
Lelscan
Manga scantrad 

Thx a lot

**Comment by Skittyblock** [comment]
Please make separate issues for separate source issues, and make sure to mention what's not work (e.g. if the home page isn't loading at all or just the chapters)
