### ISSUE TITLE
HentaiVN pages don't load

### ISSUE THREAD

**Issue by ptcutican** [Skittyblock/aidoku-community-sources#672]
HentaiVN can get manga list, chapter list. But cannot read even with online/offline mode (Only some newest manga readable, older manga cannot read) 
![image](https://github.com/Skittyblock/aidoku-community-sources/assets/87488259/2872af68-3bc2-4f6c-814a-c7f2c8d12ed0)
![image](https://github.com/Skittyblock/aidoku-community-sources/assets/87488259/c957dfda-1c1c-44bf-aa85-1dade268e297)

**Comment by Skittyblock** [comment]
please make separate issues for separate sources
