### ISSUE TITLE
Luminous scans not working

### ISSUE THREAD

**Issue by Jydn-sys** [Skittyblock/aidoku-community-sources#686]
Luminous scans not working, but the website works
![IMG_5436](https://github.com/Skittyblock/aidoku-community-sources/assets/174726960/bb86ba60-f7fb-4e04-83b2-8132a669c576)

**Comment by Aeonss** [comment]
@Skittyblock Fixed in PR 691

**Comment by Skittyblock** [comment]
put "Closes #whatever" in the PR and it'll close automatically on merge
