### ISSUE TITLE
Reaper - not loading

### ISSUE THREAD

**Issue by AloyKSA** [Skittyblock/aidoku-community-sources#693]
Reaper Scans source does not load, the Safari Icon on the top opens the website, and it requires a cloudflare check every time, not sure if this is the reason ![image](https://github.com/user-attachments/assets/2a994d5c-c8b5-44f4-ab4a-ba49c1f47dde)

**Comment by Aeonss** [comment]
Can't replicate

**Comment by the1gamerdude** [comment]
Happened to mine as well. No logs were made when it failed to load favorited series from Asura as a source. 

My fix was to uninstall Asura Scans as a source, re-add the source. Then migrate it into itself as the old series were broken. 

Broken as in new chapters were marked as unavailable (on the resume reading button). When migrating most did not have series art and authors were “unknown”. The migration generally found all the chapters and fixed it.

**Comment by yamaijia7** [comment]
It's showing this empty browse for me as well.

**Comment by yamaijia7** [comment]
Not loading for me as well. Safari doesn't do Cloudflare checks for me tho.
