### ISSUE TITLE
French Source Down (update please) | 🟥

### ISSUE THREAD

**Issue by 2145s** [Skittyblock/aidoku-community-sources#701]
Hi, all french sources are down and cannot beb used could you please update them ?
Phenix Scan working but the good one like Mangas Origines / Sushi Scan / Manga Scan trad and reaper won't work.
Also if you can add anime sama source it will be really good ! Thx

**Comment by FoxyDr3am** [comment]
First your report is going to get deleted cuz you need to make a report for each source and secondly some of them has been reported a while ago

**Comment by FoxyDr3am** [comment]
#654
