### ISSUE TITLE
ComicK is down

### ISSUE THREAD

**Issue by CadLee** [Skittyblock/aidoku-community-sources#727]
All Mangas and Manhwas from ComicK aren’t loading any chapters and once source is opened in ‘Browse’ it’s empty.

**Comment by CadLee** [comment]
> Did you try reinstalling comick? It is working for me unless it was already fixed. 

Yup that's the first thing I did. It still shows no mangas when I open it

**Comment by yamaijia7** [comment]
How about the safari button on the top. Does it load the website for you there?

**Comment by CadLee** [comment]
> How about the safari button on the top. Does it load the website for you there? 

Yes it does load the ComicK website. But never loads the manga in the extension

**Comment by yamaijia7** [comment]
Sorry. I'm not sure how to help anymore as it's working for me. Only other thing I can think of is if you have a forked version.

**Comment by CadLee** [comment]
I'm not sure whether the extension had an update or anything that made it like this because after the new Aidoku Update it was working well, it's just recently it started to bug out like this

**Comment by yamaijia7** [comment]
Actually. Hiperdex is doing the same thing for me as well. Safari works but the browse is empty

**Comment by Skittyblock** [comment]
I can't reproduce this. ComicK works fine for me. You must have some other issue with your network or something.

**Comment by CadLee** [comment]
Okay I found a fix and it worked. I went to settings and cleared network Cache. This might also help with your HiperDex issue.

**Comment by CadLee** [comment]
Okay now manga/manhwas appear in browse but many of the manhwa are now missing chapters, for example for Eleceed from ComicK shows only first 3 chapters but if I go to the website from the Safari button it has all 300+

**Comment by yamaijia7** [comment]
Tried the reset but doesn't work for hiperdex
