### ISSUE TITLE
Manga-Chan source crash 

### ISSUE THREAD

**Issue by North-02** [Skittyblock/aidoku-community-sources#733]
Since today Manga-chan source and any manga from this source is crashing the app. 

I have few titles from their source and once i try to update the manga library with pulling down from top gesture it also crashes.

Got this issue both on ipad and iphone. 

Would be glad if you fix <3

**Comment by aphronyx** [comment]
probably the same issue: Aidoku/Aidoku#468
should be fixed in the next app update, or you can downgrade to `0.6.8`
