### ISSUE TITLE
Asura Scans can't download every chapters

### ISSUE THREAD

**Issue by Kareylo** [Skittyblock/aidoku-community-sources#781]
Since #762, we can't download any chapter.
The source only downloads one or two pages max.
If we open the chapter without downloading, there's no problem.
I though I was the only one, but more and more people complaining about it on Discord.

Maybe it's a Aidoku issue, but I only have that issue on that source

**Comment by Skittyblock** [comment]
this is likely something aidoku the app will have to work around. there's an issue on the app repo already
