### ISSUE TITLE
French sources please please..

### ISSUE THREAD

**Issue by hatsuussw** [Skittyblock/aidoku-community-sources#784]
Hello, can you resolve the problem of French sources? It's horrible for us. 
https://anime-sama.fr/
https://sushiscan.net/
https://lelscanfr.com/ 
that would be great already.. thanku...

**Comment by Skittyblock** [comment]
please make separate issues for separate source issues, and make sure to mention what's not work (e.g. if the home page isn't loading at all or just the chapters). I think there are already some existing issues though
