### ISSUE TITLE
NHentai uses WebP format now, newly uploaded things don’t load

### ISSUE THREAD

**Issue by PinkBlossom3** [Skittyblock/aidoku-community-sources#794]
As of this week NHentai and HentaiFox started using WebP image format for all pages in their chapters apart from the covers, images will not load anymore only old mangas uploaded onto these site will work, the covers still use JPG on newly uploaded things, please update the sources to read WebP

**Comment by Skittyblock** [comment]
please make separate issues for separate sources

**Comment by Skittyblock** [comment]
closed by #800
