### ISSUE TITLE
Source request 

### ISSUE THREAD

**Issue by AbdullahKQ** [Skittyblock/aidoku-community-sources#796]
https://olympustaff.com/

https://stellarsaber.pro/

https://lekmanga.net/

https://mangakakalot.com/

https://toonclash.com/

https://manga4life.com/

https://novelcool.com/

https://boxmanhwa.com/

I tested the app and it was great thanks for the devs for the hard work and i wanted to help and give you the best sources that isn’t available in the app i’m sure this app will be our Tachiyomi for iphone🫡

**Comment by Skittyblock** [comment]
please make separate issues for separate source requests so that we can track them, and make sure they don't exist already. manga4life is already a source (under the name mangasee), #73 is already requested, etc.
