### ISSUE TITLE
Label Request: Language Labels

### ISSUE THREAD

**Issue by aphronyx** [Skittyblock/aidoku-community-sources#824]
It would be helpful to introduce language labels (e.g., English, Korean, Mandarin(Chinese)) in issues to allow for better filtering and categorisation of issues based on the language.

**Comment by NeKoOuO** [comment]
Need this

**Comment by Skittyblock** [comment]
I made some and added them to a few of the issues (im kinda too lazy to go through all of em though) -- ill try and make sure to add them in the future for new issues
