### ISSUE TITLE
Library not updating on iPad

### ISSUE THREAD

**Issue by lennypangpang** [Skittyblock/aidoku-community-sources#832]
As per the title - Library not updating on iPad - Can manually update on iOS by pulling down
Happens for both Comick and Mangadex
For example, Mayonaka Heart Tune should have Ch. 58 released, but I'm not receiving it on iPad. 

iPadOS 18.2 - iPad Pro 11 in M2, App version 0.6.10

**Comment by Skittyblock** [comment]
this is the wrong repo to submit issues to, but im pretty sure this is just user error. check your library update conditions. the titles wont update automatically unless you have all the other chapters read

**Comment by lennypangpang** [comment]
Point is though, I can manually update on iOS but can't on iPadOS, not sure if this is a bug or anything

**Comment by Skittyblock** [comment]
you can pull down on the left half of the screen to refresh (ik it's slightly unintuitive)
